version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: testcase_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testmanagement
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - testcase_network
    restart: unless-stopped

  web:
    build: .
    container_name: testcase_web
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=mysql+pymysql://root:password@db:3306/testmanagement?charset=utf8mb4
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - db
    networks:
      - testcase_network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  testcase_network:
    driver: bridge
