services:
  db:
    image: mysql:8.0
    container_name: test_management_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testmanagement
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql-config:/etc/mysql/conf.d
    networks:
      - test_network
    # Performance optimizations for MySQL 8.0
    command: --default-authentication-plugin=mysql_native_password 
             --innodb-buffer-pool-size=256M 
             --innodb-flush-log-at-trx-commit=2 
             --innodb-flush-method=O_DIRECT
             --max-connections=100
             --thread-cache-size=16
             --table-open-cache=2000
             --tmp-table-size=64M
             --max-heap-table-size=64M
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      timeout: 10s
      retries: 5
      interval: 5s
      start_period: 30s

  web:
    build: .
    container_name: test_management_web
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=mysql+pymysql://root:password@db:3306/testmanagement?charset=utf8mb4
      - PYTHONUNBUFFERED=1
      - FLASK_DEBUG=0
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads
    networks:
      - test_network
    restart: unless-stopped
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

volumes:
  mysql_data:

networks:
  test_network:
    driver: bridge
