apiVersion: v1
kind: ConfigMap
metadata:
  name: test-management-config
  namespace: test-management
  labels:
    app: test-management-tool
data:
  FLASK_ENV: "production"
  PYTHONUNBUFFERED: "1"
  FLASK_DEBUG: "0"
  SESSION_TIMEOUT_MINUTES: "30"
  UPLOAD_FOLDER: "/app/uploads"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: test-management
  labels:
    app: test-management-tool
    component: database
data:
  my.cnf: |
    [mysqld]
    default-authentication-plugin=mysql_native_password
    innodb-buffer-pool-size=256M
    innodb-flush-log-at-trx-commit=2
    innodb-flush-method=O_DIRECT
    max-connections=100
    thread-cache-size=16
    table-open-cache=2000
    tmp-table-size=64M
    max-heap-table-size=64M
